# Generated by Django 5.0.6 on 2026-07-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_chat_tables_and_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_user_id_d23b30_idx',
            old_name='activity_l_user_id_2e8d21_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_action__9e4610_idx',
            old_name='activity_l_action__c80302_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_a4dd5c_idx',
            old_name='notificatio_user_id_4d65c1_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_e4c995_idx',
            old_name='notificatio_created_4964ad_idx',
        ),
    ]
