# Generated by Django 6.0.6 on 2026-07-22 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_rename_activity_l_user_id_2e8d21_idx_activity_lo_user_id_d23b30_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message_receipts',
                'indexes': [models.Index(fields=['user', 'read_at'], name='chat_messag_user_id_e3b95a_idx')],
                'constraints': [models.UniqueConstraint(fields=('message_id', 'user'), name='uq_chat_receipt_message_user')],
            },
        ),
    ]
